name: Validate

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate-hacs:
    name: HACS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: HACS Action
        uses: hacs/action@22.5.0
        with:
          category: integration
